# Base de datos en memoria H2 (dev)
spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Deshabilitar Eureka en dev (no hace falta tenerlo corriendo)
eureka.client.enabled=false

# Silenciar logs de Eureka
logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN
