# Puerto por defecto de Eureka
server.port=8761

# Configuracion del servidor
eureka.instance.hostname=localhost

# Le decimos que NO intente registrarse a si mismo (porque este ES el servidor)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/